version: '3.8'
services:
  db:
    image: postgres:15.3-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  traefik:
    image: traefik:v2.10.4
    container_name: traefik
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - --providers.file.filename=/file-config.yml
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-provider-dev.yml:/file-config.yml:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`) && Path(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      
volumes:
  db:
    driver: local
  node_modules:
    driver: local