# fly.toml app configuration file generated for doko on 2023-09-18T20:16:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "doko"
primary_region = "ams"

[build]
  image = "docker.io/library/doko-backend:0.0.1-SNAPSHOT"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
