# bump version
name: Bump version
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'
      - id: github-tag
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
    outputs:
      version: ${{ steps.github-tag.outputs.new_tag }}
  call-release-workflow:
    uses: dhenne/doko/.github/workflows/release.yml@main
    needs: bump
    with:
      version: ${{ needs.bump.outputs.version }}
    secrets:
      OCI_REGISTRY_USER: ${{ secrets.OCI_REGISTRY_USER }}
      OCI_REGISTRY_PASS: ${{ secrets.OCI_REGISTRY_PASS }}
